// WEB PAGES ARE STATIC 
const express=require("express");
const URL = require("../models/url");
const { restrictTO } = require("../middlewear/auth");
const router =express.Router();

router.get('/admin/urls',restrictTO(["ADMIN"]),async(req,res)=>{
    const allurls=await URL.find({});
    return res.render("home",{
        urls:allurls,
    });
});
// only goive the url generated by the current user
router.get('/', restrictTO , async(req,res)=>{
    // if(!req.user)  return res.redirect('/login');
    const allurls = await URL.find({createdBy:req.user._id});
    // return res.render("home");
    return res.render("home",{
        urls:allurls,
    });
});

router.get("/signup",(req,res)=>{
    return res.render("signup");
});
router.get("/login",(req,res)=>{
    return res.render("login");
});
// look into the home .ejs
// when the form is submited with the post 
// request
module.exports=router;